title: Kayla Berg
logo: /PXL_20230418_223428923.jpg
description: Data and Business Analyst 
author: [LinkedIn](www.linkedin.com/in/kayla-berg-74203a222)
social-network-links: [LinkedIn](www.linkedin.com/in/kayla-berg-74203a222)
#show_downloads: true
theme: jekyll-theme-minimal
